[build]
  command = "npm run build"  # Replace with your build command if needed
[[redirects]]
  from = "/*"
  to = "/table-responsive.html"  # Replace with the name of your main HTML file
  status = 200
